krypton6@krypton:~$ mkdir /tmp/allenwest1
krypton6@krypton:/tmp$ cd /tmp/allenwest1
krypton6@krypton:/tmp/allenwest1$ ln -s /krypton/krypton6/keyfile.dat .
krypton6@krypton:/tmp/allenwest1$ python -c "print 'A'*1000" > a
krypton6@krypton:/tmp/allenwest1$ /krypton/krypton6/encrypt6 a b
krypton6@krypton:/tmp/allenwest1$ cat b; echo
EICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOC
KRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFU
EOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYC
PFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRF
XYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNS
IRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZKTHNSIRFXYCPFUEOCKRNEICTDGYIYZ
krypton6@krypton:/tmp/allenwest1$ python -c "print 'A'*30 + 'B'*30 + 'C'*30" >a
krypton6@krypton:/tmp/allenwest1$ /krypton/krypton6/encrypt6 a b
krypton6@krypton:/tmp/allenwest1$ cat b; echo
EICTDGYIYZKTHNSIRFXYCPFUEOCKRNFJDUEHZJZALUIOTJSGYZDQGVFPDLSOGKEVFIAKABMVJPUKTHZAERHWGQEMTP
krypton6@krypton:/tmp/allenwest1$ cat /krypton/krypton6/krypton7; echo
PNUKLYLWRQKGKBE
krypton6@krypton:/tmp/allenwest1$ cat >a.py
key = 'EICTDGYIYZKTHNSIRFXYCPFUEOCKRN'
ct = 'PNUKLYLWRQKGKBE'
 
pt = ''
for i in range(len(ct)):
    tmp = ord(ct[i]) - ord(key[i])
    if tmp < 0: tmp += 26
    tmp += ord('A')
    pt += chr(tmp)
print pt
krypton6@krypton:/tmp/allenwest1$ python a.py 
LFSRISNOTRANDOM
.
.
.
// END OF KRYPTON!
